import 'course.dart';

final sampleInstitutes = <Institute>[
  const Institute(
    id: 'inst_smash_pro',
    orgId: 'org_smash_pro',
    name: 'Pullela Champions Badminton Academy',
    description:
        'Leading badminton development academy with certified national level coaches, fitness trainers and match video analytics.',
    logoImage:
        'https://images.unsplash.com/photo-1626224583764-f87db24ac4ea',
    isVerified: true,
    type: InstituteType.privateInstitute,
    categoryId: 'sports_fitness',
    address: 'Gachibowli Stadium Complex, Old Mumbai Hwy',
    city: 'Hyderabad',
    phone: '+91 98765 11223',
    whatsapp: '+91 98765 11223',
    mode: CourseMode.offline,
    timingsText: '06:00 AM - 09:00 PM',
    images: [
      'https://images.unsplash.com/photo-1626224583764-f87db24ac4ea',
      'https://images.unsplash.com/photo-1544717305-2782549b5136',
    ],
    amenities: [
      'BWF Synthetic Courts',
      'Video Analytics Room',
      'Fitness Gym',
      'Parking',
      'Physiotherapy Clinic',
    ],
  ),
  const Institute(
    id: 'inst_ace_iit',
    orgId: 'org_ace_iit',
    name: 'ACE Premier IIT-JEE & NEET Academy',
    description:
        'Premier coaching institute for competitive engineering and medical entrance examinations with top faculty and proven track record.',
    logoImage:
        'https://images.unsplash.com/photo-1523240795612-9a054b0db644',
    isVerified: true,
    type: InstituteType.privateInstitute,
    categoryId: 'academics',
    address: 'Room 301, Silicon Valley Complex, Madhapur',
    city: 'Hyderabad',
    phone: '+91 98765 22334',
    whatsapp: '+91 98765 22334',
    mode: CourseMode.hybrid,
    timingsText: '08:00 AM - 08:00 PM',
    images: [
      'https://images.unsplash.com/photo-1523240795612-9a054b0db644',
      'https://images.unsplash.com/photo-1497633762265-9d179a990aa6',
    ],
    amenities: [
      'Smart Classrooms',
      'Digital Library',
      'Doubt Clearing Booths',
      'Air Conditioned',
      'Test Analysis Lab',
    ],
  ),
  const Institute(
    id: 'inst_codemasters',
    orgId: 'org_codemasters',
    name: 'CodeMasters Full-Stack & AI Academy',
    description:
        'Modern tech academy specializing in mobile, full-stack, cloud architecture, and applied Generative AI systems.',
    logoImage:
        'https://images.unsplash.com/photo-1517245386807-bb43f82c33c4',
    isVerified: true,
    type: InstituteType.privateInstitute,
    categoryId: 'tech_coding',
    address: 'Mindspace IT Park, Hitech City',
    city: 'Hyderabad',
    phone: '+91 98765 33445',
    whatsapp: '+91 98765 33445',
    mode: CourseMode.hybrid,
    timingsText: '09:00 AM - 07:00 PM',
    images: [
      'https://images.unsplash.com/photo-1517245386807-bb43f82c33c4',
    ],
    amenities: [
      'High-Speed Fiber WiFi',
      'Project Labs',
      'Mentorship Pods',
      'Cafeteria',
    ],
  ),
];

final sampleCourses = <Course>[
  Course(
    id: 'cls_badminton_jr',
    instituteId: 'inst_smash_pro',
    title: 'Junior Elite Badminton Performance Batch',
    description:
        'Structured training program focusing on agility footwork, smash power, tactical rally building, and tournament fitness.',
    mode: CourseMode.offline,
    durationWeeks: 12,
    feeAmount: 9000,
    discountAmount: 1350,
    instructorName: 'Coach Srinivas Rao',
    coverImage: 'https://images.unsplash.com/photo-1626224583764-f87db24ac4ea',
    status: 'published',
    instituteName: 'Pullela Champions Badminton Academy',
    instituteVerified: true,
    instituteCity: 'Court 1-4, Gachibowli Stadium Complex, Hyderabad',
    categoryId: 'sports_fitness',
    contactPhone: '+91 98765 11223',
    batches: [
      CourseBatch(
        id: 'batch_badminton_1',
        courseId: 'cls_badminton_jr',
        label: 'Morning Performance Batch',
        startsOn: DateTime.now().subtract(const Duration(days: 1)),
        endsOn: DateTime.now().add(const Duration(days: 90)),
        capacity: 15,
        enrolledCount: 11,
        timing: '06:00 AM - 07:30 AM',
        feeAmount: 3500,
        mode: CourseMode.offline,
        categorySlug: 'sports_fitness',
        subject: 'Badminton Coaching',
        todaysTopic: 'Smash Angle Control & Fast Baseline Recovery',
        highlightTag: 'LIVE NOW',
        daysOfWeek: const [1, 3, 5, 6],
        ageGroup: '8 - 16 Years',
        skillLevel: 'Intermediate to Advanced',
      ),
      CourseBatch(
        id: 'batch_badminton_2',
        courseId: 'cls_badminton_jr',
        label: 'Weekend Smash & Tactics Clinic',
        startsOn: DateTime.now().add(const Duration(days: 3)),
        endsOn: DateTime.now().add(const Duration(days: 90)),
        capacity: 12,
        enrolledCount: 8,
        timing: '04:30 PM - 06:00 PM (Sat, Sun)',
        feeAmount: 3200,
        mode: CourseMode.offline,
        categorySlug: 'sports_fitness',
        subject: 'Badminton Tactics & Sparring',
        todaysTopic: 'Doubles Rotation & Serve Return Positioning',
        highlightTag: 'WEEKEND BATCH',
        daysOfWeek: const [6, 7],
        ageGroup: '10 - 18 Years',
        skillLevel: 'Intermediate to Advanced',
      ),
    ],
    faculty: const [
      CourseFaculty(
        id: 'fac_1',
        courseId: 'cls_badminton_jr',
        instituteId: 'inst_smash_pro',
        name: 'Coach Srinivas Rao',
        role: 'Chief Coach',
        designation: 'Chief Coach (BWF Level 3)',
        department: 'B.P.Ed (Physical Education), Osmania University',
        qualification: 'B.P.Ed (Physical Education), Osmania University',
        experienceText: '14+ Yrs',
        studentsTrained: 1250,
        teachingPhilosophy:
            'Discipline in footwork builds confidence in rallies. We train each student to think two shots ahead.',
        photoUrl:
            'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d',
        bio:
            'Former Indian National Badminton player and Chief Junior State Selector. Coach Srinivas has trained over 1,200 aspiring shuttlers over 14+ years, producing 18 national-level junior medalists. His coaching combines biometric video analysis, explosive footwork conditioning, and mental resilience drills.',
        skills: [
          'Badminton',
          'Endurance & Agility',
          'Tournament Tactics',
          'Smash Biomechanics',
        ],
        certifications: [
          'BWF (Badminton World Federation) Level 3 High Performance Coach',
          'Ex-National Badminton Championship Gold Medalist (Men\'s Doubles)',
          'NIS (National Institute of Sports) Certified Master Coach',
          'Certified Sports Injury Prevention & First-Aid Specialist',
        ],
        achievements: [
          'Mentored 18 National Junior Ranking Tournament Finalists',
          'Awarded Best Youth Badminton Coach of Telangana (2022)',
          'Head Selector for South Zone Under-17 Championship Team',
        ],
        isActive: true,
      ),
    ],
  ),
  Course(
    id: 'cls_jee_advanced_physics',
    instituteId: 'inst_ace_iit',
    title: 'JEE Advanced Physics Masterclass & Problem Solving',
    description:
        'High-yield conceptual physics drills, previous 15-year Advanced question analysis, and time-saving shortcuts for Top 500 aspirants.',
    mode: CourseMode.hybrid,
    durationWeeks: 24,
    feeAmount: 32000,
    discountAmount: 6400,
    instructorName: 'Dr. Arvind Verma',
    coverImage: 'https://images.unsplash.com/photo-1523240795612-9a054b0db644',
    status: 'published',
    instituteName: 'ACE Premier IIT-JEE & NEET Academy',
    instituteVerified: true,
    instituteCity: 'Room 301, Silicon Valley Complex, Madhapur, Hyderabad',
    categoryId: 'academics',
    contactPhone: '+91 98765 22334',
    batches: [
      CourseBatch(
        id: 'batch_jee_1',
        courseId: 'cls_jee_advanced_physics',
        label: 'Evening Masterclass',
        startsOn: DateTime.now(),
        endsOn: DateTime.now().add(const Duration(days: 180)),
        capacity: 30,
        enrolledCount: 24,
        timing: '05:00 PM - 07:00 PM',
        feeAmount: 6500,
        mode: CourseMode.hybrid,
        categorySlug: 'academics',
        subject: 'Physics & Advanced Mechanics',
        todaysTopic: 'Rotational Dynamics & Torque Conservation Matrix',
        highlightTag: 'TODAY 05:00 PM',
        daysOfWeek: const [1, 2, 3, 4, 5, 6],
        ageGroup: '15 - 19 Years (Class 11, 12 & Droppers)',
        skillLevel: 'Advanced / Competitive',
      ),
    ],
    faculty: const [
      CourseFaculty(
        id: 'fac_2',
        courseId: 'cls_jee_advanced_physics',
        instituteId: 'inst_ace_iit',
        name: 'Dr. Arvind Verma',
        role: 'Head of Physics',
        designation: 'Head of Physics & Senior Mentor',
        qualification: 'Ph.D IIT Madras • Ex-Senior Allen Faculty',
        experienceText: '16+ Yrs Exp',
        photoUrl:
            'https://images.unsplash.com/photo-1500648767791-00dcc994a43e',
        bio:
            'Ph.D in Theoretical Physics from IIT Madras with over 16 years of IIT-JEE mentoring experience. Over 40 of his students achieved Top 100 All India Ranks.',
        skills: [
          'Classical Mechanics',
          'Electrodynamics',
          'Modern Physics',
          'Exam Time Strategy',
        ],
        certifications: [
          'Ph.D Physics - IIT Madras',
          'National Physics Olympiad Mentor',
        ],
        isActive: true,
      ),
    ],
  ),
  Course(
    id: 'cls_fullstack_ai_bootcamp',
    instituteId: 'inst_codemasters',
    title: 'Full-Stack Development & Generative AI Bootcamp',
    description:
        'Live interactive coding batch covering Flutter, Android Jetpack Compose, React/Next.js, FastAPI backends, and Gemini AI agent integration.',
    mode: CourseMode.hybrid,
    durationWeeks: 16,
    feeAmount: 24000,
    discountAmount: 4800,
    instructorName: 'Vikram Aditya',
    coverImage: 'https://images.unsplash.com/photo-1517245386807-bb43f82c33c4',
    status: 'published',
    instituteName: 'CodeMasters Full-Stack & AI Academy',
    instituteVerified: true,
    instituteCity: 'Mindspace IT Park, Hitech City, Hyderabad',
    categoryId: 'tech_coding',
    contactPhone: '+91 98765 33445',
    batches: [
      CourseBatch(
        id: 'batch_fs_1',
        courseId: 'cls_fullstack_ai_bootcamp',
        label: 'Weekend Professional Batch',
        startsOn: DateTime.now().add(const Duration(days: 2)),
        endsOn: DateTime.now().add(const Duration(days: 120)),
        capacity: 25,
        enrolledCount: 19,
        timing: '10:00 AM - 01:00 PM (Sat, Sun)',
        feeAmount: 5000,
        mode: CourseMode.hybrid,
        categorySlug: 'tech_coding',
        subject: 'Software Engineering & GenAI',
        todaysTopic: 'Agentic Workflows & Multi-Modal LLM Apps',
        highlightTag: 'WEEKEND BATCH',
        daysOfWeek: const [6, 7],
        ageGroup: 'College Students & Working Professionals',
        skillLevel: 'Beginner to Industry Ready',
      ),
    ],
    faculty: const [
      CourseFaculty(
        id: 'fac_3',
        courseId: 'cls_fullstack_ai_bootcamp',
        instituteId: 'inst_codemasters',
        name: 'Vikram Aditya',
        role: 'Principal Tech Instructor',
        designation: 'Principal Tech Instructor',
        qualification: 'B.Tech CSE • Ex-Google Senior Tech Lead',
        experienceText: '10+ Yrs Exp',
        photoUrl:
            'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7',
        bio:
            'Former Senior Tech Lead at Google. Specializes in building modern scalable cross-platform systems and generative AI tooling.',
        skills: [
          'Flutter',
          'Android Jetpack Compose',
          'Python / GenAI',
          'Cloud Architecture',
        ],
        certifications: [
          'Google Certified Cloud Architect',
          'TensorFlow Developer Certified',
        ],
        isActive: true,
      ),
    ],
  ),
];
