import 'package:flutter/material.dart';

import '../../../booking/presentation/screens/invoice_screen.dart'
    as booking_invoice;

/// Compatibility route adapter: PROD booking receipts are generated by the
/// existing booking invoice screen, not the Phase-only commerce receipt RPC.
class ReceiptScreen extends StatelessWidget {
  const ReceiptScreen({super.key, required this.bookingId});

  final String bookingId;

  @override
  Widget build(BuildContext context) =>
      booking_invoice.InvoiceScreen(bookingId: bookingId);
}
