/**
 * Mirror of `E2eIds` in lib/core/widgets/test_id.dart.
 * Kept in sync by test/tool/e2e_ids_contract_test.dart — change both together.
 */
export const Ids = {
  loginEmail: 'login_email',
  loginPassword: 'login_password',
  loginSubmit: 'login_submit',
  loginError: 'login_error',
  loginForgotPassword: 'login_forgot_password',
  loginRegister: 'login_register',
  otpChannel: 'otp_channel',
  otpContact: 'otp_contact',
  otpSend: 'otp_send',
  otpCode: 'otp_code',
  otpSubmit: 'otp_submit',
  logout: 'logout',
  searchInput: 'search_input',
  venueFavorite: 'venue_favorite',
  bookNow: 'book_now',
  bookingEventType: 'booking_event_type',
  slotPicker: 'slot_picker',
  bookingConfirm: 'booking_confirm',
  bookingConfirmDialog: 'booking_confirm_dialog',
  bookingSignIn: 'booking_sign_in',
  bookingHistory: 'booking_history',
  bookingCancelConfirm: 'booking_cancel_confirm',
  bookingsTabUpcoming: 'bookings_tab_upcoming',
  bookingsTabCompleted: 'bookings_tab_completed',
  bookingsTabCancelled: 'bookings_tab_cancelled',
  bookingRefundConfirm: 'booking_refund_confirm',
  checkoutSummary: 'checkout_summary',
  paymentMethodOnline: 'payment_method_online',
  paymentMethodVenue: 'payment_method_venue',
  paymentPay: 'payment_pay',
  paymentMessage: 'payment_message',
  paymentVerifying: 'payment_verifying',
  paymentPending: 'payment_pending',
  paymentError: 'payment_error',
  paymentDone: 'payment_done',
  holdExpired: 'hold_expired',
  bookingSuccess: 'booking_success',
  errorRetry: 'error_retry',
  profileOwnerDashboard: 'profile_owner_dashboard',
  profileAdminDashboard: 'profile_admin_dashboard',
  ownerDashboard: 'owner_dashboard',
  ownerActionBookings: 'owner_action_bookings',
  ownerActionVenues: 'owner_action_venues',
  ownerDecisionConfirm: 'owner_decision_confirm',
  availabilityAddSlot: 'availability_add_slot',
  availabilitySlotLabel: 'availability_slot_label',
  availabilitySlotStart: 'availability_slot_start',
  availabilitySlotEnd: 'availability_slot_end',
  availabilitySlotPrice: 'availability_slot_price',
  availabilitySlotSave: 'availability_slot_save',
  adminDashboard: 'admin_dashboard',
  nav: (destinationId: string) => `nav_${destinationId}`,
  venueCard: (venueId: string) => `venue_card_${venueId}`,
  slot: (slotId: string) => `slot_${slotId}`,
  bookingCard: (bookingId: string) => `booking_card_${bookingId}`,
  bookingCancel: (bookingId: string) => `booking_cancel_${bookingId}`,
  bookingRefund: (bookingId: string) => `booking_refund_${bookingId}`,
  bookingPay: (bookingId: string) => `booking_pay_${bookingId}`,
  bookingStatus: (bookingId: string, dbStatus: string) => `booking_status_${bookingId}_${dbStatus}`,
  ownerBookingCard: (bookingId: string) => `owner_booking_card_${bookingId}`,
  ownerBookingApprove: (bookingId: string) => `owner_booking_approve_${bookingId}`,
  ownerBookingReject: (bookingId: string) => `owner_booking_reject_${bookingId}`,
  ownerVenueCard: (venueId: string) => `owner_venue_card_${venueId}`,
  ownerVenuePublish: (venueId: string) => `owner_venue_publish_${venueId}`,
  ownerVenueAvailability: (venueId: string) => `owner_venue_availability_${venueId}`,
  ownerVenueState: (venueId: string, state: 'published' | 'unpublished') => `owner_venue_state_${venueId}_${state}`,
  availabilitySlot: (label: string) => `availability_slot_${label}`,
  availabilitySlotState: (label: string, state: 'active' | 'inactive') => `availability_slot_state_${label}_${state}`,
} as const;

export const Tab = { home: 'home', search: 'search', bookings: 'bookings', profile: 'profile' } as const;
